# This workflow will install Python dependencies and build the application
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyInstaller Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"
    - name: Extract version from setting.py
      run: |
        $version = uv run python -c "from app.common.setting import VERSION; print(VERSION)"
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV
    - name: Build with PyInstaller
      run: |
        uv run pyinstaller_build.py
    - name: Setup Inno Setup
      run: |
        choco install innosetup -y
    - name: Create Inno Setup script
      run: |
        @"
        [Setup]
        AppName=SuperAppStore
        AppVersion=${{ env.APP_VERSION }}
        AppId={{36E4AA33-3464-48E9-A418-CDAE5D3CA041}}
        DefaultDirName={autopf}\SuperAppStore
        DefaultGroupName=SuperAppStore
        OutputBaseFilename=SuperAppStore_${{ env.APP_VERSION }}-Setup
        ; 优化压缩设置
        Compression=lzma2/ultra64
        SolidCompression=yes
        InternalCompressLevel=max
        WizardStyle=modern
        SetupIconFile=App.ico
        
        [Files]
        Source: "build\SuperAppStore\*"; DestDir: "{app}"; Flags: recursesubdirs
        
        [Icons]
        Name: "{group}\SuperAppStore"; Filename: "{app}\SuperAppStore.exe"
        Name: "{commondesktop}\SuperAppStore"; Filename: "{app}\SuperAppStore.exe"
        "@ | Out-File -FilePath "installer.iss" -Encoding utf8
    - name: Build installer
      run: |
        iscc installer.iss
    - name: Rename installer
      run: |
        Move-Item -Path "Output\SuperAppStore_${{ env.APP_VERSION }}-Setup.exe" -Destination "SuperAppStore_${{ env.APP_VERSION }}-Setup.exe"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SuperAppStore-${{ env.APP_VERSION }}
        path: SuperAppStore_${{ env.APP_VERSION }}-Setup.exe
