# This workflow will install Python dependencies and build the application
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install altgraph==0.17.4 darkdetect==0.8.0 packaging==25.0 pefile==2023.2.7 pyqt-fluent-widgets==1.8.3 pyqt5==5.15.11 pyqt5-frameless-window==0.7.3 pyqt5-qt5==5.15.2 pyqt5-sip==12.17.0 pywin32==310 pywin32-ctypes==0.2.3 setuptools==80.9.0 nuitka
    - name: Build with Nuitka
      run: |
        python win.py
    - name: Setup Inno Setup
      run: |
        choco install innosetup -y
    - name: Create Inno Setup script
      run: |
        @"
        [Setup]
        AppName=SuperAppStore
        AppVersion=1.0.0
        AppId={{36E4AA33-3464-48E9-A418-CDAE5D3CA041}}
        DefaultDirName={autopf}\SuperAppStore
        DefaultGroupName=SuperAppStore
        OutputBaseFilename=SuperAppStore_Setup
        ; 优化压缩设置
        Compression=lzma2/ultra64
        SolidCompression=yes
        InternalCompressLevel=max
        WizardStyle=modern
        SetupIconFile=App.ico
        
        [Files]
        Source: "dist\main.dist\*"; DestDir: "{app}"; Flags: recursesubdirs
        
        [Icons]
        Name: "{group}\SuperAppStore"; Filename: "{app}\SuperAppStore.exe"
        Name: "{commondesktop}\SuperAppStore"; Filename: "{app}\SuperAppStore.exe"
        
        [Run]
        Filename: "{app}\SuperAppStore.exe"; Description: "启动应用"; Flags: nowait postinstall skipifsilent
        "@ | Out-File -FilePath "installer.iss" -Encoding utf8
    - name: Build installer
      run: |
        iscc installer.iss
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path dist/main.dist -DestinationPath SuperAppStore.zip
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SuperAppStore-artifacts
        path: |
          SuperAppStore.zip
          Output/SuperAppStore_Setup.exe
